type Query {
  # a friend, by id
  friend(id: ID!): Friend
  # all the friends
  allFriends: [Friend]
  # a dog, by id
  dog(id: ID!): Dog
  # all the dogs
  allDogs: [Dog]
  # a cat, by id
  cat(id: ID!): Cat
  # all the cats
  allCats: [Cat]
  # a hat, by id
  hat(id: ID!): Hat
  # all the hats
  allHats: [Hat]
}